# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: python:3.6.3
#      - run: |
#      docker cp . bookings_api:/bookings_api

    working_directory: /bookings_api

    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip

          name: Install dependencies
          command: |
            python setup.py install

      - run:
          name: Run tests
          command: |
            flask test

        - run:
          name: Check coverage
          command: |
            flask coverage
